---
# tasks file for install Asterisk PostgreSQL NodeJS Nginx
#- name: Include distribution dependency variables
#  include_vars: "{{ item }}"
#  with_items:
#    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}.yml"
#- name: Install required packages
#  include_tasks: "{{ item }}"
#  with_items:
#    - "{{ ansible_distribution_file_variety }}-{{ ansible_distribution_major_version }}-install_required_packages.yml"

- include_tasks: RedHat-7-install_required_packages.yml
- include_tasks: postgresql.yml
- include_tasks: nginx.yml
- include_tasks: asterisk.yml
- include_tasks: node.yml
- include_tasks: push_configs.yml
- include_tasks: firewalld.yml
- include_tasks: project.yml