---
- name: Create a directory if it does not exist
  file:
    path: /opt/rusnarbank
    state: directory
    mode: 715

#- name: Checkout a github repo
#  git:
#    repo: https://github.com/ProVitSer/MiniApiAsterisk.git
#    dest: /opt/rusnarbank

- name: Copy odbc.ini
  copy:
    src: "{{ item }}"
    dest: /opt/rusnarbank
    owner: root
    group: root
    mode: 0644
  loop: "{{ files }}"
  vars:
    files:
      - "MiniApiAsterisk/"

- name: Install requarement node.
  shell: "cd /opt/rusnarbank && npm install"

- name: Install PM2.
  npm:
    name: pm2
    global: yes

- name: start pm2 process
  command: 'pm2 start --name "api" app.js'
  become: yes
  args:
    chdir: /opt/rusnarbank

