---
- name: Copy odbcinst.ini
  template:
    src: odbcinst.ini.j2
    dest: /etc/odbcinst.ini
    owner: root
    group: root
    mode: 0644

- name: Copy odbc.ini
  template:
    src: odbc.ini.j2
    dest: /etc/odbc.ini
    owner: root
    group: root
    mode: 0644

- name: Copy Asterisk configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/asterisk/{{ item }}"
    owner: "{{ asterisk_user }}"
    group: "{{ asterisk_group }}"
    mode: 0644
  with_items:
    - cdr_odbc.conf
    - extensions.ael
    - pjsip.conf
    - res_odbc.conf
    - cdr_adaptive_odbc.conf
    - modules.conf
  notify:
    - load pbx_ael.so
    - reload res_odbc.so
    - reload cdr_adaptive_odbc.so
    - restart asterisk
    - reload ael
    - reload pjsip

- name: Create link for the record dir.
  shell: "ln -s /var/spool/asterisk/monitor /usr/share/nginx/html/"