---
- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: restart asterisk
  service:
    name: asterisk
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: restart nginx
  service: 
    name: nginx 
    state: restarted

- name: reload nginx
  service: 
    name: nginx 
    state: reloaded

- name: load pbx_ael.so
  shell: "asterisk -x 'module load pbx_ael.so'"

- name: reload res_odbc.so
  shell: "asterisk -x 'module reload res_odbc.so'"

- name: reload cdr_adaptive_odbc.so
  shell: "asterisk -x 'module reload cdr_adaptive_odbc.so'"

- name: reload ael
  shell: "asterisk -x 'ael reload'"

- name: reload pjsip
  shell: "asterisk -x 'pjsip reload'"